// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10znVK0tdOXMHmO6HymLxKrrr6GuR-mQ',
    appId: '1:19665137703:web:f83320b6abe3bb10abde02',
    messagingSenderId: '19665137703',
    projectId: 'latihan-soal-f9a2e',
    authDomain: 'latihan-soal-f9a2e.firebaseapp.com',
    storageBucket: 'latihan-soal-f9a2e.appspot.com',
    measurementId: 'G-DZ3X592KTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4oQfp_tbBa3AmPiM8LBRXtmBvQy67H6w',
    appId: '1:19665137703:android:11bdd04638b8b3d1abde02',
    messagingSenderId: '19665137703',
    projectId: 'latihan-soal-f9a2e',
    storageBucket: 'latihan-soal-f9a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr4nbd5TF4E5LTynHunrlzlexQPr73msI',
    appId: '1:19665137703:ios:5889bd4f96ff84dfabde02',
    messagingSenderId: '19665137703',
    projectId: 'latihan-soal-f9a2e',
    storageBucket: 'latihan-soal-f9a2e.appspot.com',
    androidClientId: '19665137703-al3mvsju9037mcvsispil284dhu31drc.apps.googleusercontent.com',
    iosClientId: '19665137703-66e22c1cku1njetcc7jm4nro73gs3elb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr4nbd5TF4E5LTynHunrlzlexQPr73msI',
    appId: '1:19665137703:ios:5889bd4f96ff84dfabde02',
    messagingSenderId: '19665137703',
    projectId: 'latihan-soal-f9a2e',
    storageBucket: 'latihan-soal-f9a2e.appspot.com',
    androidClientId: '19665137703-al3mvsju9037mcvsispil284dhu31drc.apps.googleusercontent.com',
    iosClientId: '19665137703-66e22c1cku1njetcc7jm4nro73gs3elb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitProject',
  );
}
